name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt nuitka ordered-set zstandard

      - name: Build exe
        run: >
          python -m nuitka
          --onefile
          --windows-console-mode=disable
          --include-data-files=config.json=config.json
          --output-filename=ClipType.exe
          --assume-yes-for-downloads
          cliptype.py

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: ClipType.exe
          generate_release_notes: true
